theme: jekyll-theme-minimal
title: About Me
description: I am an organised and analytical professional who enjoys working on collaborative projects. I have a proven history of working in a wide array of challenging disciplines and vocations. After completing a Masters in Computer Science I am now seeking employment in Software Development.
