theme: jekyll-theme-minimal
title: My Digital CV
description: I am a dedicated, curious and ambitious professional with a history that demonstrates an ability to excel in a wide array of challenging disciplines and vocations. 
I have recently completed a Master's in Computer Science and am currently seeking employment in Software Development.
